server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
