version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: edufy_auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: star4536446
    ports:
      - "5432:5432"
    volumes:
      - edufy_db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - edufy_net

  auth_service:
    build: ./services/auth_service
    image: auth_service:latest
    container_name: auth_service
    ports:
      - "8081:8080" #8081 внешний порт docker, 8080 внутренний порт Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/edufy_auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: star4536446
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    depends_on:
      - db
    restart: always
    networks:
      - edufy_net



  user_service:
      build: ./services/user_service
      image: user_service:latest
      container_name: user_service
      ports:
        - "8083:8080" #8083 внешний порт docker, внутренний порт Spring Boot
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/edufy_users
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: star4536446
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SERVER_PORT: 8080
        # SFTP to VPS Storage
        storage.sftp.host: "109.199.199.214"
        storage.sftp.port: "22"
        storage.sftp.user: "root"
        storage.sftp.keyPath: "/app/ssh/id_rsa"
        storage.sftp.keyPassphrase: "storage"
        storage.sftp.destDir: "/var/www/Edufy_Website/storage/avatars"
      depends_on:
        - db
      restart: always
      volumes:
        - /var/www/Edufy_Website/storage/avatars:/var/www/Edufy_Website/storage/avatars
        # Mount read-only SSH key for SFTP
        - /root/.ssh/storage_id_rsa:/app/ssh/id_rsa:ro
      networks:
       - edufy_net



  gateway_service:
    build: ./services/gateway_service
    image: gateway_service:latest
    container_name: gateway_service
    ports:
      - "8082:8080" #8082 внешний порт docker, 8080 внутренний порт Gin
    environment:
      AUTH_SERVICE_URL: http://auth_service:8080
      USER_SERVICE_URL: http://user_service:8080
    depends_on:
      - auth_service
      - user_service
    restart: always
    networks:
      - edufy_net

volumes:
  edufy_db_data:

networks:
  edufy_net:
    driver: bridge
