import type { UserPlan } from "./resourcesRegistry";

export type SatVideoResourceSection = "math" | "english" | "general";
export type SatVideoResourceMediaType = "video" | "file";

export type SatVideoResourceRule = {
  title: string;
  section: SatVideoResourceSection | SatVideoResourceSection[];
  mediaType: SatVideoResourceMediaType;
  requiredPlan: UserPlan;
  teacher?: string;
  href?: string;
  telegramHref?: string;
};

export const SAT_LESSONS_REPORTS_BASE_URL =
  "https://resources.edufyuzbekistan.com/materials/lessons-reports-sat";

export const satVideoResourcesRegistry: Record<string, SatVideoResourceRule> = {
  "M2QF9A7X4k": {
    title: "Introduction Lesson (Foundation)",
    section: "general",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video1403153147.mp4`,
  },
  "A7F9K2Q8m4": {
    title: "Lesson 1 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5884924978.mp4`,
  },
  "A9M4Q2kFX7": {
    title: "Lesson 1 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/1-lesson-homework.pdf`,
  },
  "F5qV2bH8Rt": {
    title: "Lesson 2 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4377113700.mp4`,
  },
  "H2pV7nL0Ka": {
    title: "Lesson 2 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/2-lesson-homework.pdf`,
  },
  "N8wR4mT7Qy": {
    title: "Lesson 3 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2339350013.mp4`,
  },
  "S2tM8bL6Xq": {
    title: "Lesson 3 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/3-lesson-homework.pdf`,
  },
  "W0pL7mH4Zq": {
    title: "Lesson 4 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6269049673.mp4`,
  },
  "Q7fH3vN0Ls": {
    title: "Lesson 4 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/4-lesson-homework.pdf`,
  },
  "D3bR9xV1Km": {
    title: "Lesson 5 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7772435514.mp4`,
  },
  "Y4cR1nK7Wp": {
    title: "Lesson 5 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/5-lesson-homework.pdf`,
  },
  "P3mL8gH1Xp": {
    title: "Lesson 6 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4455807547.mp4`,
  },
  "A0cL2rP7Xy": {
    title: "Lesson 6 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/6-lesson-homework.pdf`,
  },
  "V1nL5gH9Kt": {
    title: "Lesson 7 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video1759698401.mp4`,
  },
  "L9tN1vJ6Tb": {
    title: "Lesson 7 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/7-lesson-homework.pdf`,
  },
  "J1tR7kP2Ly": {
    title: "Lesson 8 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video3000717614.mp4`,
  },
  "F9cL3rN2Xy": {
    title: "Lesson 8 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/8-lesson-homework.pdf`,
  },
  "K0nM6xJ7Lp": {
    title: "Lesson 9 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5662825282.mp4`,
  },
  "S9pJ4gL0Ly": {
    title: "Lesson 9 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/9-lesson-homework.pdf`,
  },
  "K1tN6vJ3Tb": {
    title: "Lesson 10 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6673839533.mp4`,
  },
  "H9pX0xQ5Lp": {
    title: "Lesson 10 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/10-lesson-homework.pdf`,
  },
  "P2nL8gH4Kt": {
    title: "Lesson 11 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2913730344.mp4`,
  },
  "N5kM3rP7Mb": {
    title: "Lesson 11 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/11-lesson-homework.pdf`,
  },
  "L0mF6vN2Xp": {
    title: "Lesson 12 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6393801182.mp4`,
  },
  "R7pJ1gL8Ly": {
    title: "Lesson 12 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/12-lesson-homework.pdf`,
  },
  "A9f3K2mQ7B": {
    title: "Lesson 13 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5839201746.mp4`,
  },
  "x8P0LZ4dW2": {
    title: "Lesson 13 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/13-lesson-homework.pdf`,
  },
  "M5R1aT9CqE": {
    title: "Lesson 14 - Writing (Foundation) (1)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7493018625.mp4`,
  },
  "Q4eS8m6Y1D": {
    title: "Lesson 14 - Writing (Foundation) (2)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video9164827031.mp4`,
  },
  "7BvFJ2n0XK": {
    title: "Lesson 14 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/14-lesson-homework.pdf`,
  },
 "ZC9A5x0H7P": {
    title: "Lesson 15 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6041958273.mp4`,
  },
  "3NfK8R2M5Q": {
    title: "Lesson 15 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/15-lesson-homework.pdf`,
  },
 "L7Y0W9dA4S": {
    title: "Lesson 16 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8724501936.mp4`,
  },
  "P2m6XQF8C1": {
    title: "Lesson 16 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/16-lesson-homework.pdf`,
  },
 "g4K9M2Q8v1": {
    title: "Lesson 17 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8372504916.mp4`,
  },
  "t7X1B5l3f9": {
    title: "Lesson 17 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/17-lesson-homework.pdf`,
  },
 "R2D8P6A0Z4": {
    title: "Lesson 18 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2946157830.mp4`,
  },
  "Y5C3N7H1W8": {
    title: "Lesson 18 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/18-lesson-homework.pdf`,
  },
 "V0L6Q9M2S7": {
    title: "Lesson 19 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5603871924.mp4`,
  },
  "J8F1K4X5T3": {
    title: "Lesson 19 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/19-lesson-homework.pdf`,
  },
 "N3Q7V2B8L5": {
    title: "Lesson 20 - Writing (Foundation) (1)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4728901356.mp4`,
  },
 "H6X1F9D4R0": {
    title: "Lesson 20 - Writing (Foundation) (2)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6852394710.mp4`,
  },
  "Z5M2K8C1W7": {
    title: "Lesson 20 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/20-lesson-homework.pdf`,
  },
 "F8C1N6X4B9": {
    title: "Lesson 21 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5173096824.mp4`,
  },
 "L0J7R5V8Q3": {
    title: "Lesson 21 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/21-lesson-homework.pdf`,
  },
 "W4D9K2M7Q1": {
    title: "Lesson 22 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8641203957.mp4`,
  },
  "S6N3F8L0R5": {
    title: "Lesson 22 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/22-lesson-homework.pdf`,
  },
 "T7B2X5Q8L3": {
    title: "Lesson 23 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7398562410.mp4`,
  },
  "H1V9C4M6R0": {
    title: "Lesson 23 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/23-lesson-homework.pdf`,
  },
 "K9M4X2L7B5": {
    title: "Lesson 24 - Writing (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2957140836.mp4`,
  },
  "Q0R8C1N6D3": {
    title: "Lesson 24 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/24-lesson-homework.pdf`,
  },
 "Z6F2M9X5K1": {
    title: "Lesson 25 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video9142763508.mp4`,
  },
  "R8L0C4Q7B3": {
    title: "Lesson 25 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/25-lesson-homework.pdf`,
  },
 "M7Q4Z2X9C5": {
    title: "Lesson 26 - Writing (Foundation) (1)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4726190835.mp4`,
  },
 "B0R6L8K1F3": {
    title: "Lesson 26 - Writing (Foundation) (2)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8063519742.mp4`,
  },
  "Y5D9N2C7QX": {
    title: "Lesson 26 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/26-lesson-homework.pdf`,
  },
 "V3K7M1Q8L2": {
    title: "Lesson 27 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8613957402.mp4`,
  },
  "H5C9X4R0B6": {
    title: "Lesson 27 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/27-lesson-homework.pdf`,
  },
 "T8N3F6L1Q4": {
    title: "Lesson 28 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7041829365.mp4`,
  },
  "Z2M7K5C9V0": {
    title: "Lesson 28 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/28-lesson-homework.pdf`,
  },
 "R4X9B2M7K5": {
    title: "Lesson 29 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2386094751.mp4`,
  },
  "Q1L6F8C3V0": {
    title: "Lesson 29 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/29-lesson-homework.pdf`,
  },
 "J7C2M5Q9L4": {
    title: "Lesson 30 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4918276305.mp4`,
  },
  "H0K8X3R6B1": {
    title: "Lesson 30 - Homework (Foundation) (1)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/30-lesson-homework.pdf`,
  },
  "H0Q8X3W6B6": {
    title: "Lesson 30 - Homework (Foundation) (2)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/30-lesson-homework-new.pdf`,
  },
 "F5N2L8Q1X7": {
    title: "Lesson 31 - Reading (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6753049182.mp4`,
  },
  "V3K9C4M0R6": {
    title: "Lesson 31 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/31-lesson-homework.pdf`,
  },
 "P6X2L9Q4M1": {
    title: "Lesson 32 - Writing (Foundation)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8396172054.mp4`,
  },
  "T8C3R5K0B7": {
    title: "Lesson 32 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/32-lesson-homework.pdf`,
  },
 "Z4M7K1C8V2": {
    title: "Lesson 33 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video1529846370.mp4`,
  },
  "H9Q3L5X0R6": {
    title: "Lesson 33 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/33-lesson-homework.pdf`,
  },
 "B7K2M5Q9L3": {
    title: "Lesson 35 - Writing (Foundation) (1)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4703162958.mp4`,
  },
 "F1X6C4R8V0": {
    title: "Lesson 35 - Writing (Foundation) (2)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6935820147.mp4`,
  },
  "N3L8T2Q7K5": {
    title: "Lesson 35 - Homework (Foundation)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/34-lesson-homework.pdf`,
  },
 "Y5M2K8C1V7": {
    title: "Lesson 36 - Math (Foundation)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8057293614.mp4`,
  },
  "R0L4X9Q3B6": {
    title: "Lesson 36 - Homework (Foundation)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/35-lesson-homework.pdf`,
  },
 "M8Q3K5L2X7": {
    title: "Lesson 1 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video9285074163.mp4`,
  },
  "C0R9B6F1V4": {
    title: "Lesson 1 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/1-lesson-sat.pdf`,
  },
 "K2X9M7Q4L5": {
    title: "Lesson 2 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video3849602715.mp4`,
  },
  "B6R0C8F1V3": {
    title: "Lesson 2 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/2-lesson-sat.pdf`,
  },
 "X5M2Q8K9L4": {
    title: "Lesson 3 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7912634085.mp4`,
  },
  "R7B0C6F1V3": {
    title: "Lesson 3 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/3-lesson-sat.pdf`,
  },
 "R2X9C6F0B4": {
    title: "Lesson 4 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2509746318.mp4`,
  },
  "V5M1K8Q3L7": {
    title: "Lesson 4 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/4-lesson-sat.pdf`,
  },
 "N3K8M5Q1L7": {
    title: "Lesson 5 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6385912470.mp4`,
  },
  "T6C2R9X4B0": {
    title: "Lesson 5 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/5-lesson-sat.pdf`,
  },
 "J4K7M2Q9L5": {
    title: "Lesson 6 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4179082635.mp4`,
  },
  "H0C3R8X6B1": {
    title: "Lesson 6 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/6-lesson-sat.pdf`,
  },
 "T3X6C8R0B4": {
    title: "Lesson 7 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video9651324780.mp4`,
  },
  "F9M2K5Q1L7": {
    title: "Lesson 7 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/7-lesson-sat.pdf`,
  },
 "P4K9M2Q7L5": {
    title: "Lesson 8 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video3096847512.mp4`,
  },
  "V1C8R3X6B0": {
    title: "Lesson 8 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/8-lesson-sat.pdf`,
  },
 "N7M3K5Q2L8": {
    title: "Lesson 9 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7462053981.mp4`,
  },
  "T0X6C9R1B4": {
    title: "Lesson 9 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/9-lesson-sat.pdf`,
  },
 "L5K2M8Q3X7": {
    title: "Lesson 10 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video1839476205.mp4`,
  },
  "R1C9F6B0V4": {
    title: "Lesson 10 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/10-lesson-sat.pdf`,
  },
 "Q3M7K2L9X5": {
    title: "Lesson 11 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8203654719.mp4`,
  },
  "B0R6C4F1V8": {
    title: "Lesson 11 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/11-lesson-sat.pdf`,
  },
 "N4M9K2Q7L5": {
    title: "Lesson 12 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4710296853.mp4`,
  },
  "V1X6C3R8B0": {
    title: "Lesson 12 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/12-lesson-sat.pdf`,
  },
 "J7K3M5Q2L9": {
    title: "Lesson 13 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6381924705.mp4`,
  },
  "F0C8R4X6B1": {
    title: "Lesson 13 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/13-lesson-sat.pdf`,
  },
 "P5M2K8Q1L7": {
    title: "Lesson 14 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8071532946.mp4`,
  },
  "R3X9C6F0B4": {
    title: "Lesson 14 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/14-lesson-sat.pdf`,
  },
 "L8K1M3Q7X5": {
    title: "Lesson 15 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video1649205378.mp4`,
  },
  "T4C9R2B6V0": {
    title: "Lesson 15 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/15-lesson-sat.pdf`,
  },
 "N6M2K9Q4L1": {
    title: "Lesson 16 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5937842106.mp4`,
  },
  "V3X7C5R0B8": {
    title: "Lesson 16 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/16-lesson-sat.pdf`,
  },
 "H2K5M8Q3L7": {
    title: "Lesson 17 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4208651973.mp4`,
  },
  "F1C9R4X6B0": {
    title: "Lesson 17 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/17-lesson-sat.pdf`,
  },
 "L5M2K9Q4X7": {
    title: "Lesson 18 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8163954720.mp4`,
  },
  "V1C6R3B8F0": {
    title: "Lesson 18 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/18-lesson-sat.pdf`,
  },
 "H6Q2K5Q1L5": {
    title: "Lesson 19 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2549076318.mp4`,
  },
  "F3C8R4X0B7": {
    title: "Lesson 19 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/19-lesson-sat.pdf`,
  },
 "J5K2M8Q3L7": {
    title: "Lesson 20 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video3795820146.mp4`,
  },
  "T0X9C4W6B1": {
    title: "Lesson 20 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/20-lesson-sat.pdf`,
  },
 "Q4M7K1Q8L5": {
    title: "Lesson 21 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6409173528.mp4`,
  },
  "W3C9X2F6B0": {
    title: "Lesson 21 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/21-lesson-sat.pdf`,
  },
 "V1C8R4B0F7": {
    title: "Lesson 22 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5284061937.mp4`,
  },
  "L6K3Q5Q2X9": {
    title: "Lesson 22 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/22-lesson-sat.pdf`,
  },
 "aK7mP2Q8xL": {
    title: "Lesson 23 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8642301597.mp4`,
  },
  "V4cN9bR1Xq": {
    title: "Lesson 23 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/23-lesson-sat.pdf`,
  },
 "G7kL2pQ9vM": {
    title: "Lesson 24 - Math (SAT) (1)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video7150483926.mp4`,
  },
 "tC4R8bX1nK": {
    title: "Lesson 24 - Math (SAT) (2)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video2068394715.mp4`,
  },
  "H5mV0qF3xL": {
    title: "Lesson 24 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/24-lesson-sat.pdf`,
  },
 "A3vK7mQ2xL": {
    title: "Lesson 25 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video4391762058.mp4`,
  },
  "R5nC1bX8pT": {
    title: "Lesson 25 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/25-lesson-sat.pdf`,
  },
 "M4kP9vQ1xN": {
    title: "Lesson 26 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video5824916370.mp4`,
  },
  "T2cL8bR5yF": {
    title: "Lesson 26 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/26-lesson-sat.pdf`,
  },
 "H7mX2pQ5vL": {
    title: "Lesson 27 - Math (SAT)",
    section: "math",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video3619842750.mp4`,
  },
  "C1nK8bR4yT": {
    title: "Lesson 27 - Homework (SAT)",
    section: "math",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/27-lesson-sat.pdf`,
  },
 "F3vM9kQ2xP": {
    title: "Lesson 28 - Reading (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video8207364915.mp4`,
  },
  "R6cL1bT8yN": {
    title: "Lesson 28 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/28-lesson-sat.pdf`,
  },
 "G5kX2pQ8vM": {
    title: "Lesson 29 - Writing (SAT)",
    section: "english",
    mediaType: "video",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/video6392871504.mp4`,
  },
  "T1nC7bR4yL": {
    title: "Lesson 29 - Homework (SAT)",
    section: "english",
    mediaType: "file",
    requiredPlan: "premium",
    teacher: "Marstiff Teachers",
    href: `${SAT_LESSONS_REPORTS_BASE_URL}/marstiff-teachers/29-lesson-sat.pdf`,
  },
};
